### ISSUE TITLE
UnicodeDecodeError in Windows

### ISSUE THREAD

**Issue by Salingo** [google-research/arxiv-latex-cleaner#24]
Hello,

Thanks very much for this useful tool!

Recently I met a small issue when running the tool:
```
C:\>arxiv_latex_cleaner ./paper
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\arxiv_latex_cleaner.exe\__main__.py", line 4, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\arxiv_latex_cleaner\__main__.py", line 87, in <module>
    run_arxiv_cleaner(ARGS)
  File "c:\programdata\anaconda3\lib\site-packages\arxiv_latex_cleaner\arxiv_latex_cleaner.py", line 330, in run_arxiv_cleaner
    splits['tex_in_root'] + splits['tex_not_in_root'], parameters)
  File "c:\programdata\anaconda3\lib\site-packages\arxiv_latex_cleaner\arxiv_latex_cleaner.py", line 138, in _read_all_tex_contents
    os.path.join(parameters['input_folder'], fn))
  File "c:\programdata\anaconda3\lib\site-packages\arxiv_latex_cleaner\arxiv_latex_cleaner.py", line 131, in _read_file_content
    return fp.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 5722: illegal multibyte sequence
```

The reason could be that the default encoding in Windows is 'gbk'. Thus changing [`with open(filename, 'r') as fp`](https://github.com/google-research/arxiv-latex-cleaner/blob/8065adcef747558077072faafe2ece2d86d5e744/arxiv_latex_cleaner/arxiv_latex_cleaner.py#L130) to `with open(filename, 'rb', encoding='utf-8') as fp` may solve the issue.

**Comment by Salingo** [comment]
Comment: I have tested on the source code, problem solved after adding `encoding='utf-8'`.

**Comment by jponttuset** [comment]
Thanks @Salingo 
I'll add the fix to the code.

**Comment by Salingo** [comment]
@jponttuset  Thanks!

**Comment by jponttuset** [comment]
Reopening as a reminder for myself :)

**Comment by jponttuset** [comment]
Done
